from dataclasses import dataclass
from enum import Enum
from typing import List, Set
import re

from configs.config import settings


class RiskLevel(Enum):
    """Enumeration of clinical risk levels."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


@dataclass(frozen=True)
class SafetyResult:
    """Data structure representing the outcome of a safety check."""
    is_safe: bool
    risk_level: RiskLevel
    detected_keywords: List[str]
    disclaimer: str


class MedicalSafetyChecker:
    """
    Checker for medical and clinical safety in user queries and agent responses.
    
    This class provides mechanisms to detect high-risk keywords, categorize 
    risk levels, and append appropriate medical disclaimers.
    """

    STANDARD_DISCLAIMER: str = (
        "\n\n--- MEDICAL DISCLAIMER ---\n"
        "This information is for educational and informational purposes only and "
        "is not intended as professional medical advice, diagnosis, or treatment. "
        "Always seek the advice of your physician or other qualified health provider "
        "with any questions regarding a medical condition."
    )

    HIGH_RISK_DISCLAIMER: str = (
        "\n\n--- HIGH RISK WARNING ---\n"
        "URGENT: This query or response may involve high-risk clinical scenarios. "
        "This tool is NOT a diagnostic medical device. If this is an emergency, "
        "contact local emergency services immediately. All clinical decisions "
        "must be made by a licensed healthcare professional."
    )

    def __init__(self):
        """Initialize the safety checker with keywords from configuration."""
        self.high_risk_keywords: List[str] = settings.safety.prohibited_keywords
        # Additional medium risk terms for nuanced classification
        self.medium_risk_keywords: List[str] = [
            "diagnosis", "prescription", "surgery", "dosage", "side effects", 
            "contraindications", "treatment plan"
        ]

    def check_content(self, text: str) -> SafetyResult:
        """
        Analyze text content for clinical risks.
        
        Args:
            text: The text to analyze.
            
        Returns:
            A SafetyResult object containing the risk assessment.
        """
        if not settings.safety.enable_safety_filter:
            return SafetyResult(
                is_safe=True, 
                risk_level=RiskLevel.LOW, 
                detected_keywords=[], 
                disclaimer=self.STANDARD_DISCLAIMER
            )

        text_lower = text.lower()
        detected_high: List[str] = [
            kw for kw in self.high_risk_keywords 
            if re.search(rf"\b{re.escape(kw.lower())}\b", text_lower)
        ]
        
        detected_medium: List[str] = [
            kw for kw in self.medium_risk_keywords 
            if re.search(rf"\b{re.escape(kw.lower())}\b", text_lower)
        ]

        if detected_high:
            return SafetyResult(
                is_safe=False,
                risk_level=RiskLevel.HIGH,
                detected_keywords=detected_high,
                disclaimer=self.HIGH_RISK_DISCLAIMER
            )
        
        if detected_medium:
            return SafetyResult(
                is_safe=True,
                risk_level=RiskLevel.MEDIUM,
                detected_keywords=detected_medium,
                disclaimer=self.STANDARD_DISCLAIMER
            )

        return SafetyResult(
            is_safe=True,
            risk_level=RiskLevel.LOW,
            detected_keywords=[],
            disclaimer=self.STANDARD_DISCLAIMER
        )

    def append_disclaimer(self, response_text: str, safety_result: SafetyResult) -> str:
        """
        Appends the appropriate medical disclaimer to the response text.
        
        Args:
            response_text: The original response generated by the system.
            safety_result: The result of the safety check performed on the response or query.
            
        Returns:
            The response text with the disclaimer appended.
        """
        # If risk is HIGH, we might want to prepend or replace, but per requirement, 
        # we append the specific disclaimer identified in the result.
        return f"{response_text}{safety_result.disclaimer}"
